#! /bin/sh

rm -rf ./autom4te.cache ./aclocal.m4 ./configure ./config.log ./config.status libtool

find . -name "Makefile.in" | xargs rm -f
find . -name "Makefile" | xargs rm -f
find . -name "*.la" | xargs rm -f
find . -name "*.lo" | xargs rm -f
find . -name "*.loT" | xargs rm -f
find . -name "*.o" | xargs rm -f
find . -name ".deps" | xargs rm -rf
find . -name ".libs" | xargs rm -rf

find . -name "runsim" | xargs rm -f
find . -name "edit-mesh" | xargs rm -f
find . -name "test1" | xargs rm -f
find . -name "test2" | xargs rm -f
find . -name "test3" | xargs rm -f

find . -name "libTriCollide*.so" | xargs rm -f
find . -name "libRigid*.so" | xargs rm -f
find . -name "libCpuMsd*.so" | xargs rm -f
find . -name "libCudaMsd*.so" | xargs rm -f
find . -name "libCudaXfem*.so" | xargs rm -f
find . -name "*.cu.ptx" | xargs rm -f

find . -name "CMakeFiles" -type d | xargs rm -rf
find . -name "CMakeCache.txt" | xargs rm -f
find . -name "Makefile" | xargs rm -f
find . -name "cmake_install.cmake" | xargs rm -f

find . -name "*.cu.o.cmake" | xargs rm -f
find . -name "*.cu.o.depend" | xargs rm -f
find . -name "*.linkinfo" | xargs rm -f

rm -rf ./Debug
rm -f bin/*
rm -f lib/*
